# Minimal repo-managed Powerlevel10k profile.
# Run `p10k configure` later if you want to regenerate this interactively.

typeset -g POWERLEVEL9K_MODE='nerdfont-complete'
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%F{#cba6f7}❯%f '
typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs newline)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status command_execution_time background_jobs time)

typeset -g POWERLEVEL9K_DIR_FOREGROUND=189
typeset -g POWERLEVEL9K_DIR_BACKGROUND=NONE
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=103
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=150
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=216
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=203
typeset -g POWERLEVEL9K_VCS_BACKGROUND=NONE

typeset -g POWERLEVEL9K_STATUS_OK=false
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=203
typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=203
typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=203
typeset -g POWERLEVEL9K_STATUS_BACKGROUND=NONE

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=2
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=222
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=NONE

typeset -g POWERLEVEL9K_TIME_FOREGROUND=109
typeset -g POWERLEVEL9K_TIME_BACKGROUND=NONE
typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'

